### ISSUE TITLE
bookmarklets are blockable

### ISSUE THREAD

**Issue by dragon731012** [Tacogamerman/ByeBlocker#2]

**Comment by Tacogamerman** [comment]
Heres the thing buddy, I lied, and it worked.

**Comment by Tacogamerman** [comment]
Oh also you can run it in any javascript executor

**Comment by Tacogamerman** [comment]
First unblocker in vanilla js

**Comment by dragon731012** [comment]
Probably not

**Comment by op-max** [comment]
You know, bookmarklets are disabled from chrome version 116 and up...

**Comment by Tacogamerman** [comment]
Sucks for you I have edge on my school computer

**Comment by op-max** [comment]
I don't know, make something about the SmartSheet or Remind google browsers.
